import os
import webbrowser
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from pywebcopy import save_webpage


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 304)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images\download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 461, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_klasorsec = QtWidgets.QPushButton(self.groupBox)
        self.btn_klasorsec.setGeometry(QtCore.QRect(350, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.btn_klasorsec.setFont(font)
        self.btn_klasorsec.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\images\\folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_klasorsec.setIcon(icon1)
        self.btn_klasorsec.setObjectName("btn_klasorsec")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 30, 131, 51))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.lbl_site = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(9)
        font.setBold(False)
        self.lbl_site.setFont(font)
        self.lbl_site.setObjectName("lbl_site")
        self.lbl_KKlasor = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(9)
        font.setBold(False)
        self.lbl_KKlasor.setFont(font)
        self.lbl_KKlasor.setObjectName("lbl_KKlasor")
        self.line_Url = QtWidgets.QLineEdit(self.groupBox)
        self.line_Url.setGeometry(QtCore.QRect(140, 30, 201, 20))
        self.line_Url.setObjectName("line_Url")
        self.line_KKlasor = QtWidgets.QLineEdit(self.groupBox)
        self.line_KKlasor.setGeometry(QtCore.QRect(140, 60, 201, 20))
        self.line_KKlasor.setObjectName("line_KKlasor")
        self.btn_baslat = QtWidgets.QPushButton(Form)
        self.btn_baslat.setGeometry(QtCore.QRect(20, 190, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        self.btn_baslat.setFont(font)
        self.btn_baslat.setObjectName("btn_baslat")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(-10, 0, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(180, 200, 301, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 270, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(400, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        self.commandLinkButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\images\discord (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon2)
        self.commandLinkButton.setAutoDefault(False)
        self.commandLinkButton.setDefault(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(310, 0, 91, 41))
        self.commandLinkButton.clicked.connect(self.discord)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.commandLinkButton_2.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\images\github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon3)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_2.clicked.connect(self.github)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.btn_baslat.raise_()
        self.label_4.raise_()
        self.progressBar.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btn_klasorsec.clicked.connect(self.klasor_sec)
        self.btn_baslat.clicked.connect(self.indir)

    def klasor_sec(self):
        dosya_klasoru = str(QFileDialog.getExistingDirectory(self.groupBox, "Select Folder"))
        self.line_KKlasor.setText(dosya_klasoru)
        
    def indir(self):
        url = self.line_Url.text()
        klasor = self.line_KKlasor.text()
        if not klasor:
            QMessageBox.warning(self.btn_baslat, "Warning", "Please enter URL or select a folder.")
            return

        try:
            save_webpage(url, klasor, open_in_browser=False)
                         
        except Exception as e:
            QMessageBox.critical(self.btn_baslat, "Error", f"An error occurred during the download process: {str(e)}")
        else:
            QMessageBox.information(self.btn_baslat, "Information", "Download completed.")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LusCopy"))
        self.btn_klasorsec.setText(_translate("Form", "Select Folder"))
        self.lbl_site.setText(_translate("Form", "Website to Copy    :"))
        self.lbl_KKlasor.setText(_translate("Form", "Folder to Save        :"))
        self.btn_baslat.setText(_translate("Form", "Start"))
        self.label_4.setText(_translate("Form", "LUSCOPY WEB COPIER"))
        self.commandLinkButton.setText(_translate("Form", "Discord"))
        self.commandLinkButton_2.setText(_translate("Form", "GitHub"))

    def discord(self):
        webbrowser.open('https://discord.gg/CcNqPfP8qU')

    def github(self):
        webbrowser.open('https://github.com/volkancelik28')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
